### ISSUE TITLE
This api is too difficult to use. This is Golang not c!

### ISSUE THREAD

**Issue by jefurry** [Azure/golua#51]
**We needs lua5.3, But this api is too difficult to use. This is Golang not c!**
```
state.NewTableSize(0, len(osFuncs))
state.SetFuncs(osFuncs, 0)
```

**This is what we want :)**
[gopher-lua](https://github.com/yuin/gopher-lua)
```
// register functions to the table
mod := L.SetFuncs(L.NewTable(), exports)
// register other stuff
L.SetField(mod, "name", lua.LString("value"))
```

**Comment by latdev** [comment]
This is lua... Need to understand basic lua principe, before integrate them into your Go application. Nobody create simple X(Y) integration for low level controlled language like lua. Execution performance and code flow control are more necessary.

**Comment by technosophos** [comment]
I think it is safe to close this. The submitter seems to have found an alternative that fits their needs.
