### ISSUE TITLE
Is it dead?

### ISSUE THREAD

**Issue by samuelyao314** [Azure/golua#53]
The last commit is nearly two month ago. Is the project dead?

**Comment by Horaddrim** [comment]
In my humble opinion, I just think implementing the Lua interpreter is not the Azure's team top priority, I agree that we are missing some information about the project to help keep it going but, sadly, we just can wait :(

**Comment by bacongobbler** [comment]
The project is actively being developed internally, just that we don't have much to show at this time given the nature of interpreter development. We intend to use this as the engine for Helm 3. Currently we're working on getting the fundamentals in the engine cleaned up for general use.

To copy a comment made in another thread,

> Eventually we will add more documentation to the README. We honestly didn't think people would discover (let alone use) this project the day we open-sourced it. So it's been a pleasant surprise, but one that caught us off guard.

We will update the README when we have more information to share. For now I'm going to close this in favour of #36 as others are asking the same questions there. Thanks!
